#!/usr/bin/env bash
# Assert a frozen onedir payload is actually USABLE, not merely present.
#
#     .github/scripts/verify-payload.sh <payload-dir> <launcher-name>
#
# WHY THIS EXISTS
#     "the binary was produced" is a weak gate. Every check below corresponds to a
#     failure this project has actually shipped or nearly shipped:
#
#     Qt plugins      PyInstaller's Qt hook IMPORTS PySide6 at build time to find
#                     the plugin dirs. If that import fails (missing system
#                     glib/xcb on Linux) the hook silently collects NO plugins:
#                     `_internal/PySide6/Qt/` has lib/ but no plugins/, every
#                     worker passes, and the GUI dies with "no Qt platform plugin
#                     could be initialized". Reference/packaging.md.
#     worker table    Workers are reached only via importlib, so a rename drops
#                     them from the build with no error. An unknown --worker makes
#                     the launcher print the registered list; if that list is
#                     short, the hiddenimports derivation broke.
#     notices         LGPL/BSD/MIT all require attribution to accompany the
#                     binary. Generated by the spec, so absence means the
#                     generator silently failed. Reference/licensing.md.
#     OCC resources   BinXCAF .xbf persistence HARD-FAILS without the OCCT
#                     resource tree that CSF_PluginDefaults points at.
#
# Shared by ci.yml and release.yml so the gate and the shipped artifact are held
# to the same standard.
set -uo pipefail

PAYLOAD="${1:?usage: verify-payload.sh <payload-dir> <launcher-name>}"
LAUNCHER_NAME="${2:?usage: verify-payload.sh <payload-dir> <launcher-name>}"
LAUNCHER="$PAYLOAD/$LAUNCHER_NAME"
INTERNAL="$PAYLOAD/_internal"

fail=0
ok()   { echo "  ok    $1"; }
bad()  { echo "::error::$1"; fail=1; }
check(){ if [ "$1" = 0 ]; then ok "$2"; else bad "$2"; fi; }

echo "Verifying $PAYLOAD"

# ---------------------------------------------------------------- structure
[ -d "$PAYLOAD" ];  check $? "payload directory exists"
[ -f "$LAUNCHER" ]; check $? "launcher $LAUNCHER_NAME exists"
[ -d "$INTERNAL" ]; check $? "_internal/ exists"
if [ "$fail" != 0 ]; then
    echo "::error::payload is not present at all — nothing further to check"
    exit 1
fi
chmod +x "$LAUNCHER" 2>/dev/null || true

echo "  info  payload size: $(du -sh "$PAYLOAD" | cut -f1), $(find "$PAYLOAD" -type f | wc -l) files"

# ---------------------------------------------------------------- Qt plugins
# The fingerprint of the silent hook failure: Qt's lib/ present, plugins/ absent.
#
# ⚠️ THE PLUGIN PATH DIFFERS BY PLATFORM and an over-specific glob makes this
# check pass or fail for the wrong reason (measured against a real build):
#     Windows   _internal/PySide6/plugins/<category>/*.dll
#     Linux     _internal/PySide6/Qt/plugins/<category>/*.so
# So match on the `plugins/` segment under PySide6 and let the platform decide.
qt_plugins=$(find "$INTERNAL/PySide6" -path '*plugins/*' -type f 2>/dev/null | wc -l)
[ "$qt_plugins" -gt 0 ]; check $? "Qt plugins collected ($qt_plugins files)"
platform_plugins=$(find "$INTERNAL/PySide6" -path '*plugins/platforms/*' -type f 2>/dev/null | wc -l)
[ "$platform_plugins" -gt 0 ]; check $? "a Qt PLATFORM plugin is present ($platform_plugins)"

# ---------------------------------------------------------------- native stacks
occt=$(find "$INTERNAL" \( -name 'TK*.dll' -o -name 'libTK*.so*' \) 2>/dev/null | wc -l)
[ "$occt" -gt 10 ]; check $? "OCCT libraries bundled ($occt)"
[ -d "$INTERNAL/opencascade/resources" ]
check $? "OCCT resource tree present (BinXCAF .xbf save needs it)"
pxr=$(find "$INTERNAL" -path '*pxr*' -type f 2>/dev/null | wc -l)
[ "$pxr" -gt 10 ]; check $? "OpenUSD (pxr) bundled ($pxr files)"
vtk=$(find "$INTERNAL" \( -name 'vtk*.dll' -o -name 'libvtk*.so*' \) 2>/dev/null | wc -l)
[ "$vtk" -gt 10 ]; check $? "VTK libraries bundled ($vtk)"

# ---------------------------------------------------------------- attribution
[ -f "$INTERNAL/THIRD-PARTY-NOTICES.md" ]
check $? "THIRD-PARTY-NOTICES.md shipped"
[ -f "$INTERNAL/LICENSE.TXT" ]
check $? "LICENSE.TXT shipped"
if [ -f "$INTERNAL/THIRD-PARTY-NOTICES.md" ]; then
    if grep -q "None reported by the generator" "$INTERNAL/THIRD-PARTY-NOTICES.md"; then
        ok "notices report no licensing gaps"
    else
        # A gap is a warning, not a build failure: shipping a notices file that
        # names its own gaps beats shipping none. Reference/licensing.md.
        echo "::warning::THIRD-PARTY-NOTICES.md reports licensing gaps — read its Gaps section"
    fi
fi
fonts=$(find "$INTERNAL" -path '*resources/fonts/*' -name 'OFL-*' 2>/dev/null | wc -l)
[ "$fonts" -ge 2 ]; check $? "OFL font notices ship beside the fonts ($fonts)"

# GNU Readline is GPL-3.0-only with NO linking exception, so shipping it would be
# inconsistent with CellSmith's Apache-2.0 terms. It is in the conda Linux env
# (python depends on it) and is kept out by the spec: `excludes=` for the module PLUS
# a filter over BOTH a.binaries and a.datas. `excludes=` covers the module graph only,
# and readline reached the 2026-08-04 Linux payload by both of the other two routes —
# DT_NEEDED of the readline extension module (a.binaries), and PyInstaller's own numpy
# hook sweeping the conda `lib/` dir into a.datas. THIS is what makes the exclusion a fact rather
# than an intention — the notices file claims readline is absent, and a claim in a
# legal notice needs a check behind it. libhistory ships from the same source
# package and carries the same license, so it is checked too.
readline_hits=$(find "$INTERNAL" \
    \( -name 'readline*.so*' -o -name 'readline*.pyd' \
       -o -name 'libreadline*' -o -name 'libhistory*' \) \
    2>/dev/null | sort)
if [ -z "$readline_hits" ]; then n_readline=0
else n_readline=$(printf '%s\n' "$readline_hits" | wc -l); fi

# Who still NEEDs it? A bare count is not actionable, and the removal has a real
# failure mode in the other direction: if a collected library genuinely links
# libreadline, dropping the lib makes that library fail to dlopen at runtime.
# Compute the reverse dependencies either way — as the diagnosis when a hit is
# found, and as a warning when the payload is clean but a DT_NEEDED dangles.
#
# ⚠️ An EMPTY needers list is load-bearing evidence — it is what proved the 4 libs of
# CI run 2 were swept out of the conda `lib/` by PyInstaller's numpy hook rather than
# linked by anything. So say when the list is empty because `readelf` is missing, or
# the two cases are indistinguishable in the log.
readline_needers=""
readelf_ran=0
if command -v readelf >/dev/null 2>&1; then
    readelf_ran=1
    readline_needers=$(find "$INTERNAL" -name '*.so*' -type f -print0 2>/dev/null |
        while IFS= read -r -d '' so; do
            if readelf -d "$so" 2>/dev/null |
                   grep -qE 'NEEDED.*(libreadline|libhistory)'; then
                echo "${so#"$INTERNAL"/}"
            fi
        done | sort)
else
    echo "  info  readelf unavailable — DT_NEEDED reverse deps NOT computed"
fi

[ "$n_readline" -eq 0 ]
check $? "no GPL readline in the payload ($n_readline hits)"
if [ "$n_readline" -ne 0 ]; then
    while IFS= read -r h; do echo "         hit:   ${h#"$INTERNAL"/}"; done \
        <<< "$readline_hits"
    if [ -n "$readline_needers" ]; then
        echo "         pulled in as a DT_NEEDED dependency of:"
        echo "$readline_needers" | sed "s|^|         needs: |"
    elif [ "$readelf_ran" = 1 ]; then
        echo "         nothing in the payload NEEDs them — they were SWEPT in, not"
        echo "         linked (a hook globbing the conda lib/ dir into a.datas)"
    fi
    echo "         ^ excludes= cannot remove either kind; the spec must filter"
    echo "           a.binaries AND a.datas (see packaging/cellsmith.spec)"
elif [ -n "$readline_needers" ]; then
    echo "::warning::readline is correctly absent, but these bundled libraries still \
list it in DT_NEEDED and will fail to load at runtime: $(echo "$readline_needers" | tr '\n' ' ')"
fi

# ---------------------------------------------------------------- runtime
version_out=$("$LAUNCHER" --version 2>&1)
rc=$?
[ "$rc" = 0 ]; check $? "launcher --version exits 0"
echo "$version_out" | grep -qi 'cellsmith'; check $? "--version identifies the app: ${version_out%%$'\n'*}"

# An unknown worker must be REJECTED with the registered list — that list is
# derived from src.main._WORKERS via the spec's hiddenimports.
worker_out=$("$LAUNCHER" --worker __definitely_not_a_worker__ 2>&1)
worker_rc=$?
[ "$worker_rc" != 0 ]; check $? "an unknown --worker is rejected (rc=$worker_rc)"
for w in cache_build edges_build assets_build restructure_build export_step \
         export_usd export_obj export_composed; do
    echo "$worker_out" | grep -q "$w"; check $? "worker registered: $w"
done
for w in mesh_build mesh_cache_build mesh_assets_build mesh_ops_worker; do
    echo "$worker_out" | grep -q "$w"; check $? "mesh worker registered: $w"
done

echo
if [ "$fail" = 0 ]; then
    echo "Payload verification PASSED."
else
    echo "::error::Payload verification FAILED — see the errors above."
fi
exit "$fail"
