"""The distributable must carry its license attributions (`CS-140`..`CS-142`).

WHAT SILENTLY BREAKS WITHOUT THIS
  * a curated license text disappears from `packaging/licenses/` -> the notices
    file references a license it does not reproduce
  * the spec stops shipping `LICENSE.TXT` / `THIRD-PARTY-NOTICES.md` -> the binary
    goes out with no attribution at all
  * a copyleft or non-OSI package re-enters the environment (Intel MKL arrived
    once as a transitive dependency of conda-forge's numpy and shipped 25
    proprietary DLLs unnoticed)

Obligations and the reasoning behind each assertion: `Reference/licensing.md`.

Fast and CI-eligible: the generator only reads metadata, and the spec is exec'd
with stubs, so nothing is frozen.
"""

from __future__ import annotations

import importlib.util
import os
import sys
from pathlib import Path
from types import ModuleType
from typing import Any, Dict, List, Tuple

import pytest

REPO = Path(__file__).resolve().parent.parent
GENERATOR = REPO / "packaging" / "gen_third_party_notices.py"
SPEC = REPO / "packaging" / "cellsmith.spec"

#: A stub or an HTML error page would satisfy "the file exists" while reproducing
#: no license at all, so each text is matched against a phrase only it contains.
LICENSE_FINGERPRINTS = {
    "LGPL-2.1.txt": "GNU LESSER GENERAL PUBLIC LICENSE",
    "LGPL-3.0.txt": "GNU LESSER GENERAL PUBLIC LICENSE",
    "GPL-3.0.txt": "GNU GENERAL PUBLIC LICENSE",
    "FreeImage-FIPL.txt": "FreeImage Public License",
    "FTL.txt": "The FreeType Project LICENSE",
    "OCCT-LGPL-EXCEPTION.txt": "Open CASCADE exception",
    "InnoSetup.txt": "Inno Setup License",
}

#: Each entry is an obligation, not a nicety. See `Reference/licensing.md` L1-L6.
REQUIRED_PHRASES = {
    "OCCT exception's prominent-notice condition":
        "facilities provided by the Open CASCADE Technology software",
    "LGPL written offer for source":
        "Written offer for source code",
    "Qt identified as LGPLv3":
        "GNU Lesser General Public License version 3",
    "LGPLv3 relink right documented":
        "replace those",
    "FreeType FTL credit line":
        "copyright (c) The FreeType Project",
    "CellSmith's own Apache-2.0 terms":
        "Apache License, Version 2.0",
    "generated-not-hand-edited warning":
        "generated by",
}


@pytest.fixture(scope="module")
def generator() -> ModuleType:
    """Load the generator BY PATH.

    `import packaging.gen_third_party_notices` would collide with the installed
    pip `packaging` distribution - the same trap `make_icon.py` documents.
    """
    assert GENERATOR.is_file(), f"missing {GENERATOR}"
    spec = importlib.util.spec_from_file_location("cs_gen_notices", GENERATOR)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def notices(generator: ModuleType, tmp_path_factory: pytest.TempPathFactory) -> str:
    out = tmp_path_factory.mktemp("notices") / "THIRD-PARTY-NOTICES.md"
    assert generator.main(["--out", str(out)]) == 0
    return out.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def unelected_notices(generator: ModuleType,
                      tmp_path_factory: pytest.TempPathFactory) -> str:
    """Regenerate with the FreeImage election forced back to None.

    Without this the election assertions below would pass vacuously the moment an
    election is recorded - it proves the gap machinery still FIRES.
    """
    out = tmp_path_factory.mktemp("unelected") / "N.md"
    saved = generator.FREEIMAGE_ELECTION
    try:
        generator.FREEIMAGE_ELECTION = None
        assert generator.main(["--out", str(out)]) == 0
        return out.read_text(encoding="utf-8")
    finally:
        generator.FREEIMAGE_ELECTION = saved


def test_every_referenced_license_text_exists(generator: ModuleType) -> None:
    referenced = sorted({f for entry in generator._CURATED + generator._BUILD_TOOLS
                         for f in entry["licenses"]})
    assert referenced, "no license texts referenced at all"
    missing = [f for f in referenced
               if not (Path(generator.LICENSE_DIR) / f).is_file()]
    assert not missing, f"referenced but absent from packaging/licenses/: {missing}"


@pytest.mark.parametrize("filename,needle", sorted(LICENSE_FINGERPRINTS.items()))
def test_license_text_is_genuine(generator: ModuleType, filename: str,
                                 needle: str) -> None:
    path = Path(generator.LICENSE_DIR) / filename
    assert path.is_file(), f"missing {path}"
    body = path.read_text(encoding="utf-8", errors="replace")
    assert needle in body, f"{filename} does not look like the real license"
    assert "<!DOCTYPE" not in body and "<html" not in body.lower(), \
        f"{filename} looks like a fetched HTML page, not license text"


@pytest.mark.parametrize("label,needle", sorted(REQUIRED_PHRASES.items()))
def test_notices_discharge_each_obligation(notices: str, label: str,
                                           needle: str) -> None:
    assert needle in notices, f"notices are missing: {label}"


def test_notices_reproduce_texts_rather_than_linking(notices: str) -> None:
    assert "GNU LESSER GENERAL PUBLIC LICENSE" in notices
    assert len(notices) > 300_000, \
        f"only {len(notices):,} bytes - the verbatim texts are probably absent"


def test_freeimage_election_is_recorded(generator: ModuleType,
                                        notices: str) -> None:
    """FreeImage is GPL-2/GPL-3/FIPL at the DISTRIBUTOR's choice; not choosing
    leaves a GPL reading live against Apache-2.0 code."""
    assert generator.FREEIMAGE_ELECTION == "FIPL"
    assert "elects the FreeImage Public License" in notices
    assert "NO ELECTION HAS BEEN RECORDED" not in notices


def test_missing_election_is_reported_as_a_gap(unelected_notices: str) -> None:
    assert "NO ELECTION HAS BEEN RECORDED" in unelected_notices


def test_no_gaps_reported_for_the_current_environment(notices: str) -> None:
    assert "None reported by the generator" in notices, \
        "the generator reported licensing gaps - read the Gaps section it emitted"


def test_build_tooling_is_acknowledged(notices: str) -> None:
    assert "Jordan Russell" in notices and "jrsoftware.org" in notices
    assert "special exception" in notices and "PyInstaller" in notices


def test_environment_has_no_unresolved_copyleft_package(
        generator: ModuleType) -> None:
    """The rot guard: catches Intel MKL (or any GPL package) coming back.

    Calls the generator's OWN predicate rather than re-implementing the rule. The
    two used to be separate copies, which is a guarantee that they eventually
    disagree — and the shipped notices, not the test, are the thing that has to be
    right.
    """
    offenders = [f"{row['name']} {row['version']} [{row['license']}]"
                 for row in generator.collect_conda(sys.prefix)
                 if generator.unresolved_reason(row)]
    assert not offenders, f"unresolved copyleft/non-OSI packages: {offenders}"


def test_a_license_exception_resolves_a_gpl_row_but_bare_gpl_still_gaps(
        generator: ModuleType) -> None:
    """The Linux-only false positive that took `test-linux` red (2026-08-04).

    conda's Linux toolchain ships six GCC runtime libraries licensed
    `GPL-3.0-only WITH GCC-exception-3.1`; a substring match for `GPL-3.0-only`
    flags all of them. The exception is precisely the grant that permits linking
    into non-GPL programs, so it must clear the check — WITHOUT also clearing a
    bare GPL row, which is the assertion that keeps this from being a rubber stamp.
    https://www.gnu.org/licenses/gcc-exception-3.1.html
    """
    exempt = {"name": "libgcc", "version": "16.1.0",
              "license": "GPL-3.0-only WITH GCC-exception-3.1"}
    bare = {"name": "some-new-package", "version": "1.0",
            "license": "GPL-3.0-only"}
    assert generator.unresolved_reason(exempt) is None
    assert generator.unresolved_reason(bare), \
        "a bare GPL-3.0 package must still be reported as a gap"
    assert generator._spdx_exception(exempt["license"]) == "GCC-exception-3.1"
    assert generator._spdx_exception(bare["license"]) is None


def test_build_only_and_excluded_packages_are_documented_not_just_suppressed(
        generator: ModuleType, notices: str) -> None:
    """Every name-based resolution must carry its reasoning into the notices.

    Suppressing a copyleft row by name with no published reason is how a licensing
    claim becomes unauditable. `ld_impl_linux-64` is build-only (GNU `ld`, never in
    `_internal/`) and `readline` is excluded from the payload outright.
    """
    for name in (*generator._BUILD_ONLY, *generator._EXCLUDED_FROM_PAYLOAD):
        assert generator.unresolved_reason(
            {"name": name, "version": "0", "license": "GPL-3.0-only"}) is None
        reason = (generator._BUILD_ONLY.get(name)
                  or generator._EXCLUDED_FROM_PAYLOAD[name])
        assert len(reason) > 80, f"{name} resolved with no real explanation"

    # `readline` must additionally be excluded by the thing that builds the payload,
    # or the notices file would be asserting something no build enforces.
    spec_body = SPEC.read_text(encoding="utf-8")
    assert '"readline"' in spec_body, \
        "readline is claimed excluded but is not in the spec's excludes="


# --------------------------------------------------------------------------
# The spec must actually SHIP the attributions. Without this the generator can be
# perfect and the binary still go out bare.
class _Rec:
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        self.args, self.kwargs = args, kwargs


@pytest.fixture(scope="module")
def spec_datas() -> List[Tuple[str, str]]:
    captured: Dict[str, _Rec] = {}

    class Analysis(_Rec):
        def __init__(self, *a: Any, **kw: Any) -> None:
            super().__init__(*a, **kw)
            captured["analysis"] = self
            self.pure = self.scripts = self.binaries = self.datas = []

    namespace: Dict[str, Any] = {
        "SPECPATH": str(SPEC.parent), "DISTPATH": str(REPO / "dist"),
        "workpath": str(REPO / "build"), "os": os,
        "Analysis": Analysis, "EXE": _Rec, "PYZ": _Rec, "COLLECT": _Rec,
        "Tree": _Rec, "MERGE": _Rec, "BUNDLE": _Rec, "Splash": _Rec, "TOC": _Rec,
    }
    exec(compile(SPEC.read_bytes(), str(SPEC), "exec"), namespace)
    return list(captured["analysis"].kwargs.get("datas", []))


@pytest.mark.parametrize("filename", ["LICENSE.TXT", "THIRD-PARTY-NOTICES.md"])
def test_spec_ships_attribution_file(spec_datas: List[Tuple[str, str]],
                                     filename: str) -> None:
    destinations = {os.path.basename(src): dest for src, dest in spec_datas}
    assert destinations.get(filename) == ".", \
        f"{filename} not shipped at the payload root; datas={sorted(destinations)}"


def test_every_spec_data_source_exists(spec_datas: List[Tuple[str, str]]) -> None:
    missing = [src for src, _dest in spec_datas if not os.path.exists(src)]
    assert not missing, f"spec datas reference missing files: {missing}"
