site_name: !ENV SITE_NAME
site_url: "https://cellsmith.amt.onl/"
docs_dir: src
theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expanded
#    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
#    - content.action.edit
#    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
  palette:
#     - scheme: custom
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


# Admonitions
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - toc:
      permalink: true
      baselevel: 2 # Define which header level (##) to use as top level TOC. Default: 1

  # Improves bold and italic handling
  #   https://facelessuser.github.io/pymdown-extensions/extensions/betterem/
  - pymdownx.betterem:
      smart_enable: all

  # Link related features
  #   https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material

  # For creating symbols such as copyright
  #   https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/
  - pymdownx.smartsymbols

# Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Annotations
  - attr_list
  - md_in_html
  - pymdownx.superfences

# Buttons
  - attr_list

# Code Blocks
  - pymdownx.highlight:
      anchor_linenums: true
#      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ..
      check_paths: true
  - pymdownx.superfences

# Content Tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Data Tables
  - tables

# Diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Footnotes
  - footnotes

# Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

# Grids
  - attr_list
  - md_in_html

# Icons, Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Images
  - attr_list
  - md_in_html

# Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

# MathJax
  - pymdownx.arithmatex:
      generic: true

# Tooltips
  - abbr
  - attr_list
  - pymdownx.snippets


extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - include_dir_to_nav:
#      reverse_sort_directory: true
  - offline
  - include-markdown

repo_url: https://github.com/ManufacturingTechnology/CellSmith

hooks:
  - hooks/nav_merge.py
nav:
  - index.md
  - Misc: Misc

# Exclude AI from release build
exclude_docs: |
  AI/
